renaming RPM to Jenkins.
For now, I'm leaving /var/lib/hudson and the user/group name intact,
as the users might have been using the 'hudson' user, and
/var/lib/hudson can contain some big data.

diff --git a/rpm/SOURCES/jenkins.init.in b/rpm/SOURCES/jenkins.init.in
--- a/rpm/SOURCES/jenkins.init.in
+++ b/rpm/SOURCES/jenkins.init.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-#     SUSE system statup script for Hudson
+#     SUSE system statup script for Jenkins
 #     Copyright (C) 2007  Pascal Bleser
 #          
 #     This library is free software; you can redistribute it and/or modify it
@@ -19,92 +19,92 @@
 #     USA.
 #
 ### BEGIN INIT INFO
-# Provides:          hudson
+# Provides:          jenkins
 # Required-Start:    $local_fs $remote_fs $network $time $named
 # Should-Start: $time sendmail
 # Required-Stop:     $local_fs $remote_fs $network $time $named
 # Should-Stop: $time sendmail
 # Default-Start:     3 5
 # Default-Stop:      0 1 2 6
-# Short-Description: Hudson continuous build server
-# Description:       Start the Hudson continuous build server
+# Short-Description: Jenkins continuous build server
+# Description:       Start the Jenkins continuous build server
 ### END INIT INFO
 
 # Check for missing binaries (stale symlinks should not happen)
-HUDSON_WAR="@@WAR@@"
-test -r "$HUDSON_WAR" || { echo "$HUDSON_WAR not installed"; 
+JENKINS_WAR="@@WAR@@"
+test -r "$JENKINS_WAR" || { echo "$JENKINS_WAR not installed"; 
 	if [ "$1" = "stop" ]; then exit 0;
 	else exit 5; fi; }
 
 # Check for existence of needed config file and read it
-HUDSON_CONFIG=/etc/sysconfig/hudson
-test -e "$HUDSON_CONFIG" || { echo "$HUDSON_CONFIG not existing";
+JENKINS_CONFIG=/etc/sysconfig/jenkins
+test -e "$JENKINS_CONFIG" || { echo "$JENKINS_CONFIG not existing";
 	if [ "$1" = "stop" ]; then exit 0;
 	else exit 6; fi; }
-test -r "$HUDSON_CONFIG" || { echo "$HUDSON_CONFIG not readable. Perhaps you forgot 'sudo'?";
+test -r "$JENKINS_CONFIG" || { echo "$JENKINS_CONFIG not readable. Perhaps you forgot 'sudo'?";
 	if [ "$1" = "stop" ]; then exit 0;
 	else exit 6; fi; }
 
-HUDSON_PID_FILE="/var/run/hudson.pid"
+JENKINS_PID_FILE="/var/run/jenkins.pid"
 
 # Source function library.
 . /etc/init.d/functions
 
 # Read config	
-[ -f "$HUDSON_CONFIG" ] && . "$HUDSON_CONFIG"
+[ -f "$JENKINS_CONFIG" ] && . "$JENKINS_CONFIG"
 
 # Set up environment accordingly to the configuration settings
-[ -n "$HUDSON_HOME" ] || { echo "HUDSON_HOME not configured in $HUDSON_CONFIG";
+[ -n "$JENKINS_HOME" ] || { echo "JENKINS_HOME not configured in $JENKINS_CONFIG";
 	if [ "$1" = "stop" ]; then exit 0;
 	else exit 6; fi; }
-[ -d "$HUDSON_HOME" ] || { echo "HUDSON_HOME directory does not exist: $HUDSON_HOME";
+[ -d "$JENKINS_HOME" ] || { echo "JENKINS_HOME directory does not exist: $JENKINS_HOME";
 	if [ "$1" = "stop" ]; then exit 0;
 	else exit 1; fi; }
-export HUDSON_HOME
+export JENKINS_HOME
 
 # Search usable Java. We do this because various reports indicated
 # that /usr/bin/java may not always point to Java 1.5
 # see http://www.nabble.com/guinea-pigs-wanted-----Hudson-RPM-for-RedHat-Linux-td25673707.html
 for candidate in /usr/lib/jvm/java-1.6.0/bin/java /usr/lib/jvm/jre-1.6.0/bin/java /usr/lib/jvm/java-1.5.0/bin/java /usr/lib/jvm/jre-1.5.0/bin/java /usr/bin/java
 do
-  [ -x "$HUDSON_JAVA_CMD" ] && break
-  HUDSON_JAVA_CMD="$candidate"
+  [ -x "$JENKINS_JAVA_CMD" ] && break
+  JENKINS_JAVA_CMD="$candidate"
 done
 
-JAVA_CMD="$HUDSON_JAVA_CMD $HUDSON_JAVA_OPTIONS -DHUDSON_HOME=$HUDSON_HOME -jar $HUDSON_WAR"
-PARAMS="--logfile=/var/log/hudson/hudson.log --daemon"
-[ -n "$HUDSON_PORT" ] && PARAMS="$PARAMS --httpPort=$HUDSON_PORT"
-[ -n "$HUDSON_DEBUG_LEVEL" ] && PARAMS="$PARAMS --debug=$HUDSON_DEBUG_LEVEL"
-[ -n "$HUDSON_HANDLER_STARTUP" ] && PARAMS="$PARAMS --handlerCountStartup=$HUDSON_HANDLER_STARTUP"
-[ -n "$HUDSON_HANDLER_MAX" ] && PARAMS="$PARAMS --handlerCountMax=$HUDSON_HANDLER_MAX"
-[ -n "$HUDSON_HANDLER_IDLE" ] && PARAMS="$PARAMS --handlerCountMaxIdle=$HUDSON_HANDLER_IDLE"
-[ -n "$HUDSON_ARGS" ] && PARAMS="$PARAMS $HUDSON_ARGS"
+JAVA_CMD="$JENKINS_JAVA_CMD $JENKINS_JAVA_OPTIONS -DHUDSON_HOME=$JENKINS_HOME -jar $JENKINS_WAR"
+PARAMS="--logfile=/var/log/jenkins/jenkins.log --daemon"
+[ -n "$JENKINS_PORT" ] && PARAMS="$PARAMS --httpPort=$JENKINS_PORT"
+[ -n "$JENKINS_DEBUG_LEVEL" ] && PARAMS="$PARAMS --debug=$JENKINS_DEBUG_LEVEL"
+[ -n "$JENKINS_HANDLER_STARTUP" ] && PARAMS="$PARAMS --handlerCountStartup=$JENKINS_HANDLER_STARTUP"
+[ -n "$JENKINS_HANDLER_MAX" ] && PARAMS="$PARAMS --handlerCountMax=$JENKINS_HANDLER_MAX"
+[ -n "$JENKINS_HANDLER_IDLE" ] && PARAMS="$PARAMS --handlerCountMaxIdle=$JENKINS_HANDLER_IDLE"
+[ -n "$JENKINS_ARGS" ] && PARAMS="$PARAMS $JENKINS_ARGS"
 
-if [ "$HUDSON_ENABLE_ACCESS_LOG" = "yes" ]; then
-    PARAMS="$PARAMS --accessLoggerClassName=winstone.accesslog.SimpleAccessLogger --simpleAccessLogger.format=combined --simpleAccessLogger.file=/var/log/hudson/access_log"
+if [ "$JENKINS_ENABLE_ACCESS_LOG" = "yes" ]; then
+    PARAMS="$PARAMS --accessLoggerClassName=winstone.accesslog.SimpleAccessLogger --simpleAccessLogger.format=combined --simpleAccessLogger.file=/var/log/jenkins/access_log"
 fi
 
 RETVAL=0
 
 case "$1" in
     start)
-	echo -n "Starting Hudson "
-	daemon --user "$HUDSON_USER" --pidfile "$HUDSON_PID_FILE" $JAVA_CMD $PARAMS > /dev/null
+	echo -n "Starting Jenkins "
+	daemon --user "$JENKINS_USER" --pidfile "$JENKINS_PID_FILE" $JAVA_CMD $PARAMS > /dev/null
 	RETVAL=$?
 	if [ $RETVAL = 0 ]; then
 	    success
-	    echo > "$HUDSON_PID_FILE"  # just in case we fail to find it
+	    echo > "$JENKINS_PID_FILE"  # just in case we fail to find it
             MY_SESSION_ID=`/bin/ps h -o sess -p $$`
             # get PID
-            /bin/ps hww -u "$HUDSON_USER" -o sess,ppid,pid,cmd | \
+            /bin/ps hww -u "$JENKINS_USER" -o sess,ppid,pid,cmd | \
             while read sess ppid pid cmd; do
 		[ "$ppid" = 1 ] || continue
-		# this test doesn't work because Hudson sets a new Session ID
+		# this test doesn't work because Jenkins sets a new Session ID
                 # [ "$sess" = "$MY_SESSION_ID" ] || continue
-	       	echo "$cmd" | grep $HUDSON_WAR > /dev/null
+	       	echo "$cmd" | grep $JENKINS_WAR > /dev/null
 		[ $? = 0 ] || continue
 		# found a PID
-		echo $pid > "$HUDSON_PID_FILE"
+		echo $pid > "$JENKINS_PID_FILE"
 	    done
 	else
 	    failure
@@ -112,8 +112,8 @@ case "$1" in
 	echo
 	;;
     stop)
-	echo -n "Shutting down Hudson "
-	killproc hudson
+	echo -n "Shutting down Jenkins "
+	killproc jenkins
 	RETVAL=$?
 	echo
 	;;
@@ -133,14 +133,14 @@ case "$1" in
 	$0 start
 	;;
     force-reload)
-	echo -n "Reload service Hudson "
+	echo -n "Reload service Jenkins "
 	$0 try-restart
 	;;
     reload)
     	$0 restart
 	;;
     status)
-    	status hudson
+    	status jenkins
 	RETVAL=$?
 	;;
     probe)
@@ -148,7 +148,7 @@ case "$1" in
 	## argument to this init script which is required for a reload.
 	## Note: probe is not (yet) part of LSB (as of 1.9)
 
-	test "$HUDSON_CONFIG" -nt "$HUDSON_PID_FILE" && echo reload
+	test "$JENKINS_CONFIG" -nt "$JENKINS_PID_FILE" && echo reload
 	;;
     *)
 	echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
